# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mo9YbamVyJo2BqzW3CQS3DyyIrno49CC
"""

# ============================================================
# Assignment 6:
# Medians and Order Statistics & Elementary Data Structures
# Google Colab Single Cell Implementation
# ============================================================

import random
import time


# ============================================================
# PART 1: SELECTION ALGORITHMS
# ============================================================

# -----------------------------
# Randomized Quickselect
# -----------------------------

def randomized_partition(arr, low, high):

    pivot_index = random.randint(low, high)

    arr[pivot_index], arr[high] = arr[high], arr[pivot_index]

    pivot = arr[high]

    i = low

    for j in range(low, high):

        if arr[j] <= pivot:

            arr[i], arr[j] = arr[j], arr[i]

            i += 1

    arr[i], arr[high] = arr[high], arr[i]

    return i



def randomized_quickselect(arr, low, high, k):

    if low == high:
        return arr[low]


    pivot = randomized_partition(
        arr,
        low,
        high
    )


    if k == pivot:

        return arr[k]

    elif k < pivot:

        return randomized_quickselect(
            arr,
            low,
            pivot-1,
            k
        )

    else:

        return randomized_quickselect(
            arr,
            pivot+1,
            high,
            k
        )



# -----------------------------
# Deterministic Median of Medians
# -----------------------------


def insertion_sort(arr):

    for i in range(1,len(arr)):

        key = arr[i]

        j = i-1

        while j >= 0 and arr[j] > key:

            arr[j+1] = arr[j]

            j -= 1

        arr[j+1] = key


    return arr



def find_median(arr):

    arr = insertion_sort(arr)

    return arr[len(arr)//2]



def median_of_medians(arr):

    if len(arr) <= 5:

        return find_median(arr)


    groups = []

    for i in range(0,len(arr),5):

        groups.append(arr[i:i+5])


    medians=[]

    for group in groups:

        medians.append(
            find_median(group)
        )


    return median_of_medians(medians)



def partition(arr,pivot):

    left=[]

    middle=[]

    right=[]


    for value in arr:

        if value < pivot:

            left.append(value)

        elif value == pivot:

            middle.append(value)

        else:

            right.append(value)


    return left,middle,right



def deterministic_select(arr,k):

    if len(arr)==1:

        return arr[0]


    pivot = median_of_medians(arr)


    left,middle,right = partition(
        arr,
        pivot
    )


    if k < len(left):

        return deterministic_select(
            left,
            k
        )


    elif k < len(left)+len(middle):

        return pivot


    else:

        return deterministic_select(
            right,
            k-len(left)-len(middle)
        )



# ============================================================
# PERFORMANCE TESTING
# ============================================================

def test_selection_algorithms():

    sizes=[100,500,1000,5000]


    print("\nPerformance Comparison")
    print("----------------------")


    for size in sizes:

        data=random.sample(
            range(size*10),
            size
        )


        k=size//2


        arr1=data.copy()

        start=time.time()

        deterministic_select(
            arr1,
            k
        )

        median_time=time.time()-start



        arr2=data.copy()

        start=time.time()

        randomized_quickselect(
            arr2,
            0,
            len(arr2)-1,
            k
        )

        quick_time=time.time()-start


        print(
            f"Input Size {size}: "
            f"Median of Medians={median_time:.6f}s | "
            f"Quickselect={quick_time:.6f}s"
        )



# ============================================================
# PART 2: ELEMENTARY DATA STRUCTURES
# ============================================================


# -----------------------------
# Array Implementation
# -----------------------------

class CustomArray:

    def __init__(self):

        self.data=[]


    def insert(self,value):

        self.data.append(value)


    def delete(self,index):

        if index < len(self.data):

            return self.data.pop(index)


    def access(self,index):

        return self.data[index]


    def display(self):

        return self.data



# -----------------------------
# Stack Implementation
# -----------------------------

class Stack:

    def __init__(self):

        self.items=[]


    def push(self,value):

        self.items.append(value)


    def pop(self):

        if self.items:

            return self.items.pop()


    def peek(self):

        return self.items[-1]


    def display(self):

        return self.items



# -----------------------------
# Queue Implementation
# -----------------------------

class Queue:

    def __init__(self):

        self.items=[]


    def enqueue(self,value):

        self.items.append(value)


    def dequeue(self):

        if self.items:

            return self.items.pop(0)


    def display(self):

        return self.items



# -----------------------------
# Linked List Implementation
# -----------------------------

class Node:

    def __init__(self,value):

        self.value=value

        self.next=None



class LinkedList:

    def __init__(self):

        self.head=None



    def insert(self,value):

        new_node=Node(value)

        new_node.next=self.head

        self.head=new_node



    def delete(self,value):

        current=self.head

        previous=None


        while current:


            if current.value==value:


                if previous:

                    previous.next=current.next

                else:

                    self.head=current.next


                return


            previous=current

            current=current.next



    def traverse(self):

        result=[]

        current=self.head


        while current:

            result.append(
                current.value
            )

            current=current.next


        return result



# ============================================================
# DEMONSTRATION
# ============================================================


print("PART 1: SELECTION ALGORITHMS")

numbers=[20,5,10,8,30,15,3]


k=3


print(
    "4th smallest element using Median of Medians:",
    deterministic_select(
        numbers.copy(),
        k
    )
)


print(
    "4th smallest element using Quickselect:",
    randomized_quickselect(
        numbers.copy(),
        0,
        len(numbers)-1,
        k
    )
)



test_selection_algorithms()



print("\nPART 2: DATA STRUCTURES")


# Array

array=CustomArray()

array.insert(10)

array.insert(20)

array.insert(30)


print(
    "Array:",
    array.display()
)



array.delete(1)

print(
    "After deletion:",
    array.display()
)



# Stack

stack=Stack()

stack.push(100)

stack.push(200)

stack.push(300)


print(
    "Stack:",
    stack.display()
)


print(
    "Removed:",
    stack.pop()
)



# Queue

queue=Queue()

queue.enqueue("Task A")

queue.enqueue("Task B")


print(
    "Queue:",
    queue.display()
)


print(
    "Removed:",
    queue.dequeue()
)



# Linked List

linked=LinkedList()

linked.insert("Python")

linked.insert("Algorithms")

linked.insert("Data Structures")


print(
    "Linked List:",
    linked.traverse()
)


linked.delete("Algorithms")


print(
    "After deleting node:",
    linked.traverse()
)